module.exports = [
  {
    files: ['**/*.js', '**/*.html'],
    languageOptions: {
      globals: {
        AOS: 'readonly',
        FFmpeg: 'readonly',
        fetch: 'readonly',
        window: 'readonly',
        document: 'readonly',
        console: 'readonly',
        localStorage: 'readonly',
        sessionStorage: 'readonly',
        navigator: 'readonly',
        location: 'readonly',
        history: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearTimeout: 'readonly',
        clearInterval: 'readonly',
        requestAnimationFrame: 'readonly',
        cancelAnimationFrame: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        Blob: 'readonly',
        File: 'readonly',
        FileReader: 'readonly',
        FormData: 'readonly',
        Headers: 'readonly',
        Request: 'readonly',
        Response: 'readonly',
        AbortController: 'readonly',
        EventSource: 'readonly',
        WebSocket: 'readonly',
        Worker: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        global: 'readonly'
      },
      ecmaVersion: 'latest',
      sourceType: 'module'
    },
    rules: {
      'no-unused-vars': 'off',
      'no-console': 'off',
      'no-case-declarations': 'off',
      'indent': 'off',
      'no-redeclare': 'off',
      'no-inner-declarations': 'off',
      'no-empty': 'off',
      'no-undef': 'off',
      'no-prototype-builtins': 'off',
      'no-global-assign': 'off',
      'no-restricted-globals': 'off',
      'no-unsafe-negation': 'off',
      'no-unused-expressions': 'off'
    }
  }
];